### ISSUE TITLE
NYTimes误杀

### ISSUE THREAD

**Issue by JonahLee1999** [rentianyu/Ad-set-hosts#1]
大佬纽约时报误杀(用了一个国外去广告的源，不知道是不是您的，但是也先反馈下)，需要添加白名单
www.economist.com
www.nytimes.com

**Comment by rentianyu** [comment]
你说一下误杀的什么地方吗？直接网址打不开？



---原始邮件---
发件人: "JonahLee1999"<notifications@github.com&gt;
发送时间: 2020年8月18日(周二) 晚上11:07
收件人: "rentianyu/Ad-set-hosts"<Ad-set-hosts@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [rentianyu/Ad-set-hosts] NYTimes误杀 (#1)




 
大佬纽约时报误杀(用了一个国外去广告的源，不知道是不是您的，但是也先反馈下)，需要添加白名单
 www.economist.com
 www.nytimes.com

**Comment by rentianyu** [comment]
你能说一下误杀的情况吗？
比如哪个网址的哪个地方的东西加载不出来，或者说哪个网址不能访问。

**Comment by rentianyu** [comment]
> 大佬纽约时报误杀(用了一个国外去广告的源，不知道是不是您的，但是也先反馈下)，需要添加白名单
> [www.economist.com](http://www.economist.com)
> [www.nytimes.com](http://www.nytimes.com)

你能说一下误杀的情况吗？
比如哪个网址的哪个地方的东西加载不出来，或者说哪个网址不能访问。

**Comment by JonahLee1999** [comment]
啊我用的就是直接是NYTimes的app
网站是可以进去的，app除了登录界面可以，其他全不🉑

**Comment by rentianyu** [comment]
> 啊我用的就是直接是NYTimes的app
> 网站是可以进去的，app除了登录界面可以，其他全不🉑

明天再看看吧

**Comment by rentianyu** [comment]
> 啊我用的就是直接是NYTimes的app
> 网站是可以进去的，app除了登录界面可以，其他全不🉑

搞好了，你更新下吧
samizdat-graphql.nytimes.com
这个的问题，可能还有小问题，有的话你再说
