### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by yoshimo** [rentianyu/Ad-set-hosts#14]
i am not sure where you get your data from and what the goal exactly is of this list, but i think you block a bit too much

```
old.reddit.com
reddit.com
www.reddit.com
i.redd.it
i.reddit.com
it.reddit.com
m.reddit.com
reddit.map.fastly.net
redditmedia.com
redditstatic.com
oauth.reddit.com
about.reddit.com
```
Check them again, these look like required hosts to me, including images, an italian and a mobile version as well as simple authentication via Oauth protocol.

**Comment by rentianyu** [comment]
OK
