### ISSUE TITLE
PayPal误杀，导致其js、css等资源无法加载

### ISSUE THREAD

**Issue by Winnie0408** [rentianyu/Ad-set-hosts#21]
误杀网址：
www.paypalobjects.com
![image](https://github.com/rentianyu/Ad-set-hosts/assets/42741874/4dc863b8-33e8-4e75-87f9-221bae1a82d9)

加入白名单前：
![image](https://github.com/rentianyu/Ad-set-hosts/assets/42741874/1a1cd76c-1b4f-4008-bb0d-12550698ab19)

加入白名单后：
![image](https://github.com/rentianyu/Ad-set-hosts/assets/42741874/8b476c57-9072-4040-b7b9-627a813eb4bc)

**Comment by rentianyu** [comment]
已处理

**Comment by rentianyu** [comment]
> 误杀网址： [www.paypalobjects.com](http://www.paypalobjects.com) ![image](https://user-images.githubusercontent.com/42741874/270524001-4dc863b8-33e8-4e75-87f9-221bae1a82d9.png)
> 
> 加入白名单前： ![image](https://user-images.githubusercontent.com/42741874/270524520-1a1cd76c-1b4f-4008-bb0d-12550698ab19.png)
> 
> 加入白名单后： ![image](https://user-images.githubusercontent.com/42741874/270524594-8b476c57-9072-4040-b7b9-627a813eb4bc.png)

已处理
